src/app/app.module.ts
src/app/pages/Dialog/dialog-signup/dialog-signup.component.html
src/app/pages/Dialog/dialog-signup/dialog-signup.component.scss
src/app/pages/Dialog/dialog-signup/dialog-signup.component.spec.ts
src/app/pages/Dialog/dialog-signup/dialog-signup.component.ts
src/app/pages/auth/auth-routing.module.ts
src/app/pages/auth/auth.module.ts
src/app/pages/auth/signin/signin.component.html
src/app/pages/auth/signup/signup.component.html
src/app/pages/auth/signup/signup.component.spec.ts
src/app/pages/auth/signup/signup.component.ts

Se completo el diseño de signup

Se completo el diseño de signup

---

src/app/app.module.ts
src/app/pages/Dialog/dialog-change-pass/dialog-change-pass.component.html
src/app/pages/Dialog/dialog-change-pass/dialog-change-pass.component.scss
src/app/pages/Dialog/dialog-change-pass/dialog-change-pass.component.spec.ts
src/app/pages/Dialog/dialog-change-pass/dialog-change-pass.component.ts
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.html
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.scss
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.spec.ts
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.ts
src/app/pages/auth/auth-routing.module.ts
src/app/pages/auth/auth.module.ts
src/app/pages/auth/change-password/change-password.component.html
src/app/pages/auth/change-password/change-password.component.spec.ts
src/app/pages/auth/change-password/change-password.component.ts
src/app/pages/auth/recover-password/recover-password.component.html
src/app/pages/auth/recover-password/recover-password.component.spec.ts
src/app/pages/auth/recover-password/recover-password.component.ts
src/app/pages/auth/signin/signin.component.html

Se ha terminado de diseñar el flujo de recuperar contraseña

Finalise el diseño de recuperar contraseña

---

.vscode/settings.json
src/app/pages/facebook/facebook.component.html
src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/header/header.component.html
src/app/pages/facebook/header/header.component.scss
src/app/pages/facebook/header/header.component.spec.ts
src/app/pages/facebook/header/header.component.ts
src/app/pages/facebook/publications/publications.component.html
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.spec.ts
src/app/pages/facebook/publications/publications.component.ts
src/app/pages/home/header/header.component.html
src/app/pages/home/header/header.component.scss
src/app/pages/home/home.component.html
src/app/pages/home/home.component.scss
src/app/pages/home/home.module.ts

Se  ha terminado de diseñar la pantalla de publicasiones

Diseño de publicasiones

---

package-lock.json
package.json
src/app/models/respuesta.ts
src/app/models/user.ts
src/app/service/login.service.ts

agregando services con para usuario y login

agregando services con login 

---

src/app/app-routing.module.ts
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.html
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.scss
src/app/pages/Dialog/dialog-recover-pass/dialog-recover-pass.component.ts
src/app/pages/Dialog/dialog-signin/dialog-signin.component.html
src/app/pages/Dialog/dialog-signin/dialog-signin.component.scss
src/app/pages/Dialog/dialog-signin/dialog-signin.component.ts
src/app/pages/facebook/facebook-routing.module.ts
src/app/pages/facebook/facebook.component.html
src/styles.scss

Se realisaron agustes principalmente en el dialogo de verificasion de codigo y rutas

Se  realisaron ajustes para enpesar con la conexio

---

src/app/app.module.ts
src/app/authentication/signup/signup.component.html
src/app/models/user.ts
src/app/pages/Dialog/dialog-signup-error/dialog-signup-error.component.html
src/app/pages/Dialog/dialog-signup-error/dialog-signup-error.component.scss
src/app/pages/Dialog/dialog-signup-error/dialog-signup-error.component.spec.ts
src/app/pages/Dialog/dialog-signup-error/dialog-signup-error.component.ts
src/app/pages/Dialog/dialog-signup/dialog-signup.component.ts
src/app/pages/auth/signup/signup.component.html
src/app/pages/auth/signup/signup.component.ts
src/app/service/errores.service.ts
src/app/service/login.service.ts
src/environments/environment.ts
src/styles.scss

Se conecto con la base el requistro

El reguistro se conecto con la base de datos

---

src/app/models/post.model.ts
src/app/models/post.modelDTO.ts
src/app/models/response.model.ts
src/app/service/publicaciones.service.ts

Se finalizo con el mapeo de los endpoints de publicaciones

Mapeo de servicios de publicaciones

---

src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/header/header.component.html
src/app/pages/facebook/publications/publications.component.html
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/app/service/publicaciones.service.ts

Se agrega la funcionalidad para ver las publicaciones

Se agrega la funcionalidad y pantalla de publicaciones

---

src/app/app.component.scss
src/app/pages/facebook/create-post/create-post.component.html
src/app/pages/facebook/create-post/create-post.component.spec.ts
src/app/pages/facebook/create-post/create-post.component.ts
src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/header/header.component.html
src/app/pages/facebook/header/header.component.scss
src/app/pages/facebook/publications/publications.component.html
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/index.html

Se agrega la funcionalidad de publicaciones

Funcionalidad de publicaciones

---

src/app/pages/facebook/header/header.component.html
src/app/pages/facebook/publications/publications.component.html
src/app/pages/home/header/header.component.html
src/app/pages/home/header/header.component.ts
src/app/pages/home/home.component.html
src/app/pages/home/home.component.scss
src/app/pages/home/home.component.ts
src/app/pages/home/home.module.ts

Se realiso ajustes en el menu lateral

---

package-lock.json
package.json
src/app/app.module.ts
src/app/models/post.model.ts
src/app/models/post.modelDTO.ts
src/app/pages/facebook/create-post/create-post.component.html
src/app/pages/facebook/create-post/create-post.component.ts
src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/publications/publications.component.html
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/app/service/publicaciones.service.ts
src/app/shared/utils/utils.ts

Se agrega la funcionalidad de crear las publicaciones

Agregando la funcionalidad de crear publicaciones

---

src/app/pages/auth/signin/signin.component.ts
src/app/pages/dialogs/dialog-signin/dialog-signin.component.ts
src/app/pages/home/edit-user/edit-user.component.html
src/app/pages/home/edit-user/edit-user.component.scss
src/app/pages/home/edit-user/edit-user.component.spec.ts
src/app/pages/home/edit-user/edit-user.component.ts
src/app/pages/home/header/header.component.html
src/app/pages/home/header/header.component.scss
src/app/pages/home/header/header.component.ts
src/app/pages/home/home.module.ts
src/app/service/login.service.ts
src/styles.scss

Se termino con el modulo de editar perfil del usuario

Editar usuario

---

src/app/app-routing.module.ts
src/app/pages/facebook/facebook-routing.module.ts
src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/header/header.component.html
src/app/pages/facebook/header/header.component.scss
src/app/pages/facebook/my-publications/my-publications.component.html
src/app/pages/facebook/my-publications/my-publications.component.spec.ts
src/app/pages/facebook/my-publications/my-publications.component.ts
src/app/pages/facebook/publications/publications.component.html
src/app/pages/home/header/header.component.html
src/app/pages/home/home.module.ts

Se modifico el header y se creo un componete para per mis publicaciones

Crear my posts

---

src/app/models/comment.ts
src/app/pages/facebook/publications/comments/comments.component.html
src/app/pages/facebook/publications/comments/comments.component.scss
src/app/pages/facebook/publications/comments/comments.component.ts
src/app/service/comments.service.ts

Finalizando Comentarios en book face

Finalizando funcionalidad comentarios

---

src/app/pages/facebook/create-post/create-post.component.html
src/app/pages/facebook/create-post/create-post.component.ts
src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/publications/publications.component.html
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/app/pages/home/header/header.component.html
src/app/service/publicaciones.service.ts

Se agrega la funcionalidad de likes en publicaciones

Feature fix publicaciones

---

src/app/pages/facebook/facebook.module.ts
src/app/pages/facebook/publications/comments/comments.component.html
src/app/pages/facebook/publications/comments/comments.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/styles.scss

El dialog de los comentarios ya cumple con los estilos definidos

DIseño del comentarios terminado

---

src/app/pages/facebook/edit-my-post/edit-my-post.component.ts
src/app/pages/facebook/my-publications/my-publications.component.html
src/app/pages/facebook/my-publications/my-publications.component.scss
src/app/pages/facebook/publications/publications.component.scss
src/app/pages/facebook/publications/publications.component.ts
src/app/service/publicaciones.service.ts

Se corriguio el error al momento de editar las publicaciones

Correcciones en la edicion de publicaciones

---

src/app/pages/tiktok/create-post/create-post.component.html
src/app/pages/tiktok/create-post/create-post.component.spec.ts
src/app/pages/tiktok/create-post/create-post.component.ts
src/app/pages/tiktok/publications/publications.component.html
src/app/pages/tiktok/publications/publications.component.scss
src/app/pages/tiktok/publications/publications.component.ts
src/app/pages/tiktok/tiktok.module.ts
src/app/service/publicaciones.service.ts

Se agrega la funcionalidad de crear y ver publicaciones de toktik

Agregando publicaciones de toktik

---

src/app/pages/home/edit-user/edit-user.component.html
src/app/pages/home/edit-user/edit-user.component.ts
src/app/pages/home/header/header.component.html
src/app/pages/home/header/header.component.scss
src/app/pages/home/header/header.component.ts
src/app/pages/tiktok/publications/publications.component.html
src/app/pages/tiktok/publications/publications.component.scss

Se realisaron ajustes a el proyecto

Cambios de proyecto

---

src/app/pages/tiktok/comments/comments.component.html
src/app/pages/tiktok/comments/comments.component.scss
src/app/pages/tiktok/comments/comments.component.ts
src/app/pages/tiktok/publications/publications.component.html
src/app/pages/tiktok/publications/publications.component.ts

Agregando funcionalidad de los comentarios para la red social TokTik

Funcionalidad de los comentarios

---

src/app/app-routing.module.ts
src/app/pages/tiktok/my-publications/my-publications.component.html
src/app/pages/tiktok/my-publications/my-publications.component.ts
src/app/pages/tiktok/publications/publications.component.html
src/app/pages/tiktok/tiktok-routing.module.ts
src/app/pages/tiktok/tiktok.module.ts

Se realizó la creación del componente mis publicaciones

posttiktok
